import { useState, useEffect, useRef } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ActivityIndicator } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../../../shared/context/ThemeContext';
import { useTranslation } from '../../../shared/context/I18nContext';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

const MOCK_QUESTIONS = [
  { id: '1', text: 'Tell us about your experience with React Native.' },
  { id: '2', text: 'How do you handle state management in large applications?' },
  { id: '3', text: 'Describe a challenging bug you resolved.' },
  { id: '4', text: 'How do you approach testing in mobile development?' },
];

export default function InterviewPage() {
  const { theme } = useTheme();
  const { t } = useTranslation();
  const insets = useSafeAreaInsets();
  const c = theme.colors;
  const styles = createStyles(c);

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [questions, setQuestions] = useState([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isRecording, setIsRecording] = useState(false);
  const [timeLeft, setTimeLeft] = useState(180);
  const [transcript, setTranscript] = useState('');
  const [recorded, setRecorded] = useState(false);

  const timerRef = useRef(null);

  useEffect(() => {
    const timer = setTimeout(() => {
      setQuestions(MOCK_QUESTIONS);
      setLoading(false);
    }, 800);
    return () => clearTimeout(timer);
  }, []);

  useEffect(() => {
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, []);

  function formatTime(seconds) {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return `${m}:${s < 10 ? '0' : ''}${s}`;
  }

  function handleRecord() {
    if (isRecording) {
      clearInterval(timerRef.current);
      setIsRecording(false);
      setRecorded(true);
      setTranscript('This is a simulated transcript of your recorded answer. In production, this would be generated by the transcription service.');
    } else {
      setIsRecording(true);
      setTimeLeft(180);
      setRecorded(false);
      setTranscript('');
      timerRef.current = setInterval(() => {
        setTimeLeft((prev) => {
          if (prev <= 1) {
            clearInterval(timerRef.current);
            setIsRecording(false);
            setRecorded(true);
            setTranscript('This is a simulated transcript of your recorded answer.');
            return 0;
          }
          return prev - 1;
        });
      }, 1000);
    }
  }

  function handleNext() {
    if (currentIndex < questions.length - 1) {
      setCurrentIndex((i) => i + 1);
      setRecorded(false);
      setTranscript('');
    }
  }

  if (loading) {
    return (
      <View style={[styles.centered, { backgroundColor: c['surface-muted'] }]}>
        <ActivityIndicator size="large" color={c.primary} />
        <Text style={styles.loadingText}>{t("interview.loading")}</Text>
      </View>
    );
  }

  if (error) {
    return (
      <View style={[styles.centered, { backgroundColor: c['surface-muted'] }]}>
        <Ionicons name="alert-circle-outline" size={48} color={c.destructive} />
        <Text style={styles.errorText}>{error}</Text>
      </View>
    );
  }

  if (!questions.length) {
    return (
      <View style={[styles.centered, { backgroundColor: c['surface-muted'] }]}>
        <Ionicons name="document-outline" size={48} color={c['muted-foreground']} />
        <Text style={styles.emptyText}>{t("interview.no_questions")}</Text>
      </View>
    );
  }

  const current = questions[currentIndex];

  return (
    <View style={[styles.container, { backgroundColor: c['surface-muted'] }]}>
      <View style={[styles.header, { paddingTop: insets.top + 16, backgroundColor: c.sidebar }]}>
        <View style={styles.headerGradient}>
          <Ionicons name="videocam" size={28} color={c['destructive-foreground']} style={styles.headerIcon} />
          <Text style={styles.headerTitle}>{t("interview.title")}</Text>
        </View>
      </View>

      <View style={styles.body}>
        <View style={styles.bodyContent}>
          <View style={styles.progressRow}>
            <Text style={styles.progressText}>
              {t("interview.question_progress", { current: currentIndex + 1, total: questions.length })}
            </Text>
            <View style={styles.progressBar}>
              <View style={[styles.progressFill, { width: `${((currentIndex + 1) / questions.length) * 100}%` }]} />
            </View>
          </View>

          <View style={styles.questionCard}>
            <Ionicons name="help-circle-outline" size={20} color={c.primary} />
            <Text style={styles.questionText}>{current.text}</Text>
          </View>

          <View style={styles.recordingSection}>
            <View style={styles.timerRow}>
              <Ionicons name="time-outline" size={18} color={isRecording ? c.destructive : c['muted-foreground']} />
              <Text style={[styles.timerText, isRecording && { color: c.destructive }]}>
                {formatTime(timeLeft)}
              </Text>
            </View>

            <TouchableOpacity
              style={[styles.recordButton, isRecording && { backgroundColor: c.foreground }]}
              onPress={handleRecord}
              activeOpacity={0.7}
            >
              <Ionicons
                name={isRecording ? 'stop-circle' : 'radio-button-on'}
                size={24}
                color={c['destructive-foreground']}
              />
              <Text style={styles.recordButtonText}>
                {isRecording ? t("interview.stop_recording") : recorded ? t("interview.record_again") : t("interview.start_recording")}
              </Text>
            </TouchableOpacity>
          </View>

          {transcript ? (
            <View style={styles.transcriptCard}>
              <View style={styles.transcriptHeader}>
                <Ionicons name="document-text-outline" size={16} color={c.primary} />
                <Text style={styles.transcriptTitle}>{t("interview.transcript_title")}</Text>
              </View>
              <Text style={styles.transcriptText}>{transcript}</Text>
            </View>
          ) : (
            <View style={styles.transcriptEmpty}>
              <Ionicons name="mic-outline" size={32} color={c.border} />
              <Text style={styles.transcriptEmptyText}>
                {isRecording ? t("interview.recording_in_progress") : t("interview.transcript_empty")}
              </Text>
            </View>
          )}

          {recorded && currentIndex < questions.length - 1 && (
            <TouchableOpacity style={styles.nextButton} onPress={handleNext} activeOpacity={0.7}>
              <Text style={styles.nextButtonText}>{t("interview.next_question")}</Text>
              <Ionicons name="arrow-forward" size={18} color={c['destructive-foreground']} />
            </TouchableOpacity>
          )}

          {currentIndex === questions.length - 1 && recorded && (
            <View style={[styles.completeBanner, { backgroundColor: `${c.success}1a` }]}>
              <Ionicons name="checkmark-circle" size={20} color={c.success} />
              <Text style={[styles.completeText, { color: c.success }]}>{t("interview.complete")}</Text>
            </View>
          )}
        </View>
      </View>
    </View>
  );
}

function createStyles(c) { return StyleSheet.create({
  container: {
    flex: 1,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
  },
  loadingText: {
    marginTop: 12,
    color: c['muted-foreground'],
    fontSize: 15,
  },
  errorText: {
    marginTop: 12,
    color: c.destructive,
    fontSize: 15,
  },
  emptyText: {
    marginTop: 12,
    color: c['muted-foreground'],
    fontSize: 15,
    textAlign: 'center',
  },
  header: {
    paddingBottom: 24,
    paddingHorizontal: 24,
  },
  headerGradient: {
    alignItems: 'center',
  },
  headerIcon: {
    marginBottom: 6,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: c['destructive-foreground'],
  },
  body: {
    flex: 1,
  },
  bodyContent: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 40,
  },
  progressRow: {
    marginBottom: 20,
  },
  progressText: {
    fontSize: 13,
    color: c['muted-foreground'],
    fontWeight: '600',
    marginBottom: 8,
  },
  progressBar: {
    height: 6,
    backgroundColor: c.border,
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: c.primary,
    borderRadius: 3,
  },
  questionCard: {
    backgroundColor: c.card,
    borderRadius: 14,
    padding: 20,
    borderWidth: 1,
    borderColor: c.border,
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 24,
    gap: 12,
  },
  questionText: {
    fontSize: 16,
    fontWeight: '600',
    color: c.foreground,
    flex: 1,
    lineHeight: 22,
  },
  recordingSection: {
    backgroundColor: c.card,
    borderRadius: 14,
    padding: 20,
    borderWidth: 1,
    borderColor: c.border,
    alignItems: 'center',
    marginBottom: 20,
  },
  timerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 16,
  },
  timerText: {
    fontSize: 32,
    fontWeight: '800',
    color: c.foreground,
    fontVariant: ['tabular-nums'],
  },
  recordButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: c.destructive,
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 30,
  },
  recordButtonText: {
    color: c['destructive-foreground'],
    fontSize: 15,
    fontWeight: '700',
  },
  transcriptCard: {
    backgroundColor: c.card,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: c.border,
    marginBottom: 20,
  },
  transcriptHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 10,
  },
  transcriptTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: c.primary,
  },
  transcriptText: {
    fontSize: 14,
    color: c.foreground,
    lineHeight: 20,
  },
  transcriptEmpty: {
    backgroundColor: c.card,
    borderRadius: 14,
    padding: 32,
    borderWidth: 1,
    borderColor: c.border,
    alignItems: 'center',
    marginBottom: 20,
  },
  transcriptEmptyText: {
    fontSize: 13,
    color: c['muted-foreground'],
    marginTop: 8,
  },
  nextButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: c.primary,
    paddingVertical: 14,
    borderRadius: 12,
  },
  nextButtonText: {
    color: c['destructive-foreground'],
    fontSize: 15,
    fontWeight: '700',
  },
  completeBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 12,
    padding: 16,
  },
  completeText: {
    fontSize: 14,
    fontWeight: '600',
  },
}); }
