import { useState, useEffect, useRef } from 'react';
import { ScrollView, View, Text, StyleSheet, TouchableOpacity, ActivityIndicator } from 'react-native';
import { Ionicons } from '@expo/vector-icons';

const T = {
  primary: '#01497c',
  sidebar: '#012a4a',
  accent: '#468faf',
  surface: '#eef7fa',
  border: '#cfe7f2',
  foreground: '#012a4a',
  muted: '#2a6f97',
  white: '#ffffff',
};

const MOCK_QUESTIONS = [
  { id: '1', text: 'Tell us about your experience with React Native.' },
  { id: '2', text: 'How do you handle state management in large applications?' },
  { id: '3', text: 'Describe a challenging bug you resolved.' },
  { id: '4', text: 'How do you approach testing in mobile development?' },
];

export default function InterviewPage() {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [questions, setQuestions] = useState([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isRecording, setIsRecording] = useState(false);
  const [timeLeft, setTimeLeft] = useState(180);
  const [transcript, setTranscript] = useState('');
  const [recorded, setRecorded] = useState(false);

  const timerRef = useRef(null);

  useEffect(() => {
    const timer = setTimeout(() => {
      setQuestions(MOCK_QUESTIONS);
      setLoading(false);
    }, 800);
    return () => clearTimeout(timer);
  }, []);

  useEffect(() => {
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, []);

  function formatTime(seconds) {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return `${m}:${s < 10 ? '0' : ''}${s}`;
  }

  function handleRecord() {
    if (isRecording) {
      clearInterval(timerRef.current);
      setIsRecording(false);
      setRecorded(true);
      setTranscript('This is a simulated transcript of your recorded answer. In production, this would be generated by the transcription service.');
    } else {
      setIsRecording(true);
      setTimeLeft(180);
      setRecorded(false);
      setTranscript('');
      timerRef.current = setInterval(() => {
        setTimeLeft((prev) => {
          if (prev <= 1) {
            clearInterval(timerRef.current);
            setIsRecording(false);
            setRecorded(true);
            setTranscript('This is a simulated transcript of your recorded answer.');
            return 0;
          }
          return prev - 1;
        });
      }, 1000);
    }
  }

  function handleNext() {
    if (currentIndex < questions.length - 1) {
      setCurrentIndex((i) => i + 1);
      setRecorded(false);
      setTranscript('');
    }
  }

  if (loading) {
    return (
      <View style={styles.centered}>
        <ActivityIndicator size="large" color={T.primary} />
        <Text style={styles.loadingText}>Loading interview questions...</Text>
      </View>
    );
  }

  if (error) {
    return (
      <View style={styles.centered}>
        <Ionicons name="alert-circle-outline" size={48} color="#dc2626" />
        <Text style={styles.errorText}>{error}</Text>
      </View>
    );
  }

  if (!questions.length) {
    return (
      <View style={styles.centered}>
        <Ionicons name="document-outline" size={48} color={T.muted} />
        <Text style={styles.emptyText}>No questions available for this interview.</Text>
      </View>
    );
  }

  const current = questions[currentIndex];

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <View style={styles.headerGradient}>
          <Ionicons name="videocam" size={28} color={T.white} style={styles.headerIcon} />
          <Text style={styles.headerTitle}>Interview Session</Text>
          <Text style={styles.headerSubtitle}>Frontend Developer · Alice Johnson</Text>
        </View>
      </View>

      <ScrollView style={styles.body} contentContainerStyle={styles.bodyContent}>
        <View style={styles.progressRow}>
          <Text style={styles.progressText}>
            Question {currentIndex + 1} of {questions.length}
          </Text>
          <View style={styles.progressBar}>
            <View style={[styles.progressFill, { width: `${((currentIndex + 1) / questions.length) * 100}%` }]} />
          </View>
        </View>

        <View style={styles.questionCard}>
          <Ionicons name="help-circle-outline" size={20} color={T.primary} />
          <Text style={styles.questionText}>{current.text}</Text>
        </View>

        <View style={styles.recordingSection}>
          <View style={styles.timerRow}>
            <Ionicons name="time-outline" size={18} color={isRecording ? '#dc2626' : T.muted} />
            <Text style={[styles.timerText, isRecording && styles.timerActive]}>
              {formatTime(timeLeft)}
            </Text>
          </View>

          <TouchableOpacity
            style={[styles.recordButton, isRecording && styles.recordButtonActive]}
            onPress={handleRecord}
            activeOpacity={0.7}
          >
            <Ionicons
              name={isRecording ? 'stop-circle' : 'radio-button-on'}
              size={24}
              color={T.white}
            />
            <Text style={styles.recordButtonText}>
              {isRecording ? 'Stop Recording' : recorded ? 'Record Again' : 'Start Recording'}
            </Text>
          </TouchableOpacity>
        </View>

        {transcript ? (
          <View style={styles.transcriptCard}>
            <View style={styles.transcriptHeader}>
              <Ionicons name="document-text-outline" size={16} color={T.primary} />
              <Text style={styles.transcriptTitle}>Transcript</Text>
            </View>
            <Text style={styles.transcriptText}>{transcript}</Text>
          </View>
        ) : (
          <View style={styles.transcriptEmpty}>
            <Ionicons name="mic-outline" size={32} color={T.border} />
            <Text style={styles.transcriptEmptyText}>
              {isRecording ? 'Recording in progress...' : 'Your transcript will appear here'}
            </Text>
          </View>
        )}

        {recorded && currentIndex < questions.length - 1 && (
          <TouchableOpacity style={styles.nextButton} onPress={handleNext} activeOpacity={0.7}>
            <Text style={styles.nextButtonText}>Next Question</Text>
            <Ionicons name="arrow-forward" size={18} color={T.white} />
          </TouchableOpacity>
        )}

        {currentIndex === questions.length - 1 && recorded && (
          <View style={styles.completeBanner}>
            <Ionicons name="checkmark-circle" size={20} color="#155724" />
            <Text style={styles.completeText}>All questions answered. Thank you!</Text>
          </View>
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: T.surface,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: T.surface,
    padding: 32,
  },
  loadingText: {
    marginTop: 12,
    color: T.muted,
    fontSize: 15,
  },
  errorText: {
    marginTop: 12,
    color: '#dc2626',
    fontSize: 15,
  },
  emptyText: {
    marginTop: 12,
    color: T.muted,
    fontSize: 15,
    textAlign: 'center',
  },
  header: {
    backgroundColor: T.sidebar,
    paddingTop: 60,
    paddingBottom: 24,
    paddingHorizontal: 24,
  },
  headerGradient: {
    alignItems: 'center',
  },
  headerIcon: {
    marginBottom: 6,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: T.white,
  },
  headerSubtitle: {
    fontSize: 13,
    color: T.accent,
    marginTop: 2,
  },
  body: {
    flex: 1,
  },
  bodyContent: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 40,
  },
  progressRow: {
    marginBottom: 20,
  },
  progressText: {
    fontSize: 13,
    color: T.muted,
    fontWeight: '600',
    marginBottom: 8,
  },
  progressBar: {
    height: 6,
    backgroundColor: T.border,
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: T.primary,
    borderRadius: 3,
  },
  questionCard: {
    backgroundColor: T.white,
    borderRadius: 14,
    padding: 20,
    borderWidth: 1,
    borderColor: T.border,
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 24,
    gap: 12,
  },
  questionText: {
    fontSize: 16,
    fontWeight: '600',
    color: T.foreground,
    flex: 1,
    lineHeight: 22,
  },
  recordingSection: {
    backgroundColor: T.white,
    borderRadius: 14,
    padding: 20,
    borderWidth: 1,
    borderColor: T.border,
    alignItems: 'center',
    marginBottom: 20,
  },
  timerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 16,
  },
  timerText: {
    fontSize: 32,
    fontWeight: '800',
    color: T.foreground,
    fontVariant: ['tabular-nums'],
  },
  timerActive: {
    color: '#dc2626',
  },
  recordButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#dc2626',
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 30,
  },
  recordButtonActive: {
    backgroundColor: T.foreground,
  },
  recordButtonText: {
    color: T.white,
    fontSize: 15,
    fontWeight: '700',
  },
  transcriptCard: {
    backgroundColor: T.white,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: T.border,
    marginBottom: 20,
  },
  transcriptHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 10,
  },
  transcriptTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: T.primary,
  },
  transcriptText: {
    fontSize: 14,
    color: T.foreground,
    lineHeight: 20,
  },
  transcriptEmpty: {
    backgroundColor: T.white,
    borderRadius: 14,
    padding: 32,
    borderWidth: 1,
    borderColor: T.border,
    alignItems: 'center',
    marginBottom: 20,
  },
  transcriptEmptyText: {
    fontSize: 13,
    color: T.muted,
    marginTop: 8,
  },
  nextButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: T.primary,
    paddingVertical: 14,
    borderRadius: 12,
  },
  nextButtonText: {
    color: T.white,
    fontSize: 15,
    fontWeight: '700',
  },
  completeBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#d4edda',
    borderRadius: 12,
    padding: 16,
  },
  completeText: {
    color: '#155724',
    fontSize: 14,
    fontWeight: '600',
  },
});
